name: NodeJS CI - lint

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: client
      - run: npm run lint
        working-directory: client

      - run: npm ci
        working-directory: server
      - run: npm run lint
        working-directory: server
